import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AdBanner from "@/components/AdBanner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const time = new Date();

  // const currentTime = time.toDateString();
  return (
    <html lang="en">
      <body className={inter.className}>
       
          {/* <h3 className="text-center text-5xl py-9">LOGO</h3> */}

          <Navbar />
          {/* <p>{currentTime}</p> */}
          {/* 
        <div className="absolute top-96 right-0 ">
          <AdBanner />
        </div>
        <div className="absolute top-96 left-0 ">
          <AdBanner />
        </div>
     */}

          {children}
        
      </body>
    </html>
  );
}
